name: ambers_app
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  flutter_modular: ^1.1.2
  sqflite: ^1.3.0+1
  path: ^1.6.4

  flutter_project_package:
    git:
      url: https://github.com/GitHubStuff/flutter_project_package.git
  flutter_sqlite_controller:
    git:
      url: https://github.com/GitHubStuff/flutter_sqlite_controller.git
  flutter_sqlite_developer:
    git:
      url: https://github.com/GitHubStuff/flutter_sqlite_developer.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
